apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api-gateway-service
  name: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: api-gateway-service
    spec:
      containers:
        - env:
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-registry-service:8761/eureka/
          image: gorgui/api-gateway-service:latest
          name: api-gateway-service
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
