apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: billing-service
  name: billing-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: billing-service
