apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: config-service
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: config-service
    spec:
      containers:
        - env:
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-registry-service:8761/eureka/
          image: gorgui/config-service:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://config-service:9191/actuator/health
            failureThreshold: 4
            periodSeconds: 10
          name: config-service
          ports:
            - containerPort: 9191
              protocol: TCP
      restartPolicy: Always
