apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: customer-service
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: customer-service
    spec:
      containers:
        - env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-service:9191/
            - name: SPRING_DATASOURCE_PASSWORD
              value: rootpassword
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/customer_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-1:9092,kafka-2:9093
            - name: eureka.client.service-url.defaultZone
              value: http://eureka-registry-service:8761/eureka/
          image: gorgui/customer-service:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://customer-service:8082/actuator/health
            failureThreshold: 4
            periodSeconds: 10
          name: customer-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
