apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: customer_db
            - name: MYSQL_PASSWORD
              value: userpassword
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_USER
              value: user
          image: mysql:8.0
          name: mysql-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: customer-db
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: mysql-cm1
              subPath: init.sql
      restartPolicy: Always
      volumes:
        - name: customer-db
          persistentVolumeClaim:
            claimName: customer-db
        - configMap:
            items:
              - key: mysql-init.sql
                path: init.sql
            name: mysql-cm1
          name: mysql-cm1
