apiVersion: v1
kind: Service
metadata:
  name: eureka-registry-service
spec:
  type: {{ .Values.service.eurekaRegistry.type }}
  ports:
    - port: {{ .Values.service.eurekaRegistry.port }}
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: eureka-registry-service
